application:
  runtimeManifest:
    packages:
      hono:
        license: Apache-2.0
        actions:
          rest-api:
            function: src/actions/hono.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
