application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      io-graphql:
        license: Apache-2.0
        actions:
          graphql:
            function: actions/graphql/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
