application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      todo-app:
        license: Apache-2.0
        actions:
          todolist:
            function: actions/todolist/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
